// components/HeroSection.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { motion } from "framer-motion";
import dynamic from "next/dynamic";
import { MapPin, Mail, ArrowDown, Award, Briefcase, Code2, ChevronRight } from "lucide-react";
import gsap from "gsap";

const TypeAnimation = dynamic(() => import("react-type-animation").then((mod) => mod.TypeAnimation), { ssr: false });

// 极简高质感暖亮背景 (Apple Aesthetic Light Aura)
function AppleLightBackground() {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!containerRef.current) return;
    const lights = containerRef.current.querySelectorAll(".light-orb");

    lights.forEach((orb) => {
      gsap.to(orb, {
        x: "random(-30, 30)",
        y: "random(-30, 30)",
        scale: "random(0.95, 1.15)",
        opacity: "random(0.4, 0.7)",
        duration: "random(8, 12)",
        repeat: -1,
        yoyo: true,
        ease: "sine.inOut",
      });
    });
  }, []);

  return (
    <div ref={containerRef} className="absolute inset-0 pointer-events-none overflow-hidden">
      {/* 极细浅灰几何网格 */}
      <div
        className="absolute inset-0 opacity-[0.03]"
        style={{
          backgroundImage: `
            linear-gradient(rgba(0, 0, 0, 0.1) 1px, transparent 1px),
            linear-gradient(90deg, rgba(0, 0, 0, 0.1) 1px, transparent 1px)
          `,
          backgroundSize: "64px 64px",
        }}
      />
      {/* 苹果极简弥散暖光色块 */}
      <div className="light-orb absolute top-1/4 left-1/2 -translate-x-1/2 w-[650px] h-[380px] rounded-full bg-blue-200/40 blur-[130px]" />
      <div className="light-orb absolute top-1/3 left-1/3 w-[450px] h-[320px] rounded-full bg-indigo-100/50 blur-[140px]" />
      <div className="light-orb absolute bottom-1/4 right-1/3 w-[500px] h-[320px] rounded-full bg-sky-200/35 blur-[150px]" />
    </div>
  );
}

// 高级数字计数器
function AdvancedCounter({ target, suffix = "" }: { target: number; suffix?: string }) {
  const countRef = useRef<HTMLSpanElement>(null);
  const [started, setStarted] = useState(false);

  useEffect(() => {
    if (!started || !countRef.current) return;

    const obj = { value: 0 };
    gsap.to(obj, {
      value: target,
      duration: 2,
      ease: "power3.out",
      onUpdate: () => {
        if (countRef.current) {
          countRef.current.textContent = Math.floor(obj.value) + suffix;
        }
      },
    });
  }, [target, suffix, started]);

  return (
    <motion.span
      onViewportEnter={() => setStarted(true)}
      viewport={{ once: true }}
      ref={countRef}
      className="stat-number"
    >
      0{suffix}
    </motion.span>
  );
}

export default function HeroSection() {
  const sectionRef = useRef<HTMLElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!contentRef.current) return;

    const tl = gsap.timeline({
      defaults: { ease: "power3.out" },
    });

    tl.from(".hero-badge", { y: 20, opacity: 0, duration: 0.8, delay: 0.2 })
      .from(".hero-title", { y: 30, opacity: 0, duration: 1 }, "-=0.5")
      .from(".hero-subtitle", { y: 20, opacity: 0, duration: 0.8 }, "-=0.6")
      .from(".hero-typewriter", { y: 20, opacity: 0, duration: 0.6 }, "-=0.5")
      .from(".hero-bio", { y: 20, opacity: 0, duration: 0.6 }, "-=0.4")
      .from(".hero-contact", { y: 20, opacity: 0, stagger: 0.1, duration: 0.6 }, "-=0.4")
      .from(".hero-stat", { y: 25, opacity: 0, stagger: 0.1, duration: 0.6 }, "-=0.3")
      .from(".hero-cta", { y: 20, opacity: 0, stagger: 0.1, duration: 0.5 }, "-=0.3");

    return () => {
      tl.kill();
    };
  }, []);

  return (
    <section
      ref={sectionRef}
      id="home"
      className="relative min-h-screen flex items-center justify-center overflow-hidden py-24 sm:py-32"
    >
      <AppleLightBackground />

      <div ref={contentRef} className="relative z-10 container-main text-center">
        <div className="max-w-4xl mx-auto space-y-10">
          {/* 状态徽章 */}
          <div className="hero-badge flex justify-center">
            <div className="badge">
              <span className="relative flex h-2 w-2">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75" />
                <span className="relative inline-flex rounded-full h-2 w-2 bg-blue-600" />
              </span>
              Open for Opportunities
            </div>
          </div>

          {/* 名字 */}
          <div className="space-y-4">
            <h1 className="hero-title heading-display text-[clamp(3rem,8vw,6.5rem)] text-gray-900 tracking-tight">
              <span className="gradient-text-accent">李洪斌</span>
            </h1>
            <p className="hero-subtitle text-[clamp(1.1rem,2.5vw,2rem)] text-gray-500 font-light tracking-wide">
              Li Hongbin
            </p>
          </div>

          {/* 打字机效果 */}
          <div className="hero-typewriter min-h-[36px]">
            <span className="font-mono text-base sm:text-lg tracking-wider text-blue-600 font-semibold">
              <TypeAnimation
                sequence={[
                  "Cloud Native Architect", 3000,
                  "DevOps Engineer", 3000,
                  "Kubernetes Specialist", 3000,
                  "Full Stack Developer", 3000,
                ]}
                wrapper="span"
                speed={45}
                repeat={Infinity}
                cursor={true}
              />
            </span>
          </div>

          {/* 简介 */}
          <div className="hero-bio max-w-2xl mx-auto space-y-3 px-4">
            <p className="text-gray-800 text-base sm:text-lg leading-relaxed font-normal">
              深耕云原生领域的准工程师，专注于容器化、微服务架构与自动化运维。
            </p>
            <p className="text-gray-500 text-sm sm:text-base leading-relaxed">
              擅长 Kubernetes 集群优化、Serverless 架构设计、CI/CD 流水线构建。
            </p>
          </div>

          {/* 联系信息 */}
          <div className="hero-contact flex flex-col sm:flex-row flex-wrap justify-center items-center gap-4 sm:gap-8 pt-2">
            {[
              { icon: MapPin, label: "Location", value: "中国 · 重庆" },
              { icon: Mail, label: "Email", value: "yunjie.cloud@example.com" },
            ].map((item) => (
              <div key={item.label} className="flex items-center gap-3">
                <div className="w-9 h-9 rounded-lg bg-blue-50 border border-blue-100 flex items-center justify-center text-blue-600 flex-shrink-0 shadow-sm">
                  <item.icon className="w-4 h-4" />
                </div>
                <div className="text-left min-w-0">
                  <div className="text-[10px] text-gray-400 font-mono uppercase tracking-wider">
                    {item.label}
                  </div>
                  <div className="text-sm text-gray-800 font-medium">{item.value}</div>
                </div>
              </div>
            ))}
          </div>

          {/* 统计数据 */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 max-w-xl mx-auto pt-4">
            {[
              { icon: Award, label: "国家励志奖学金", value: "2024" },
              { icon: Briefcase, label: "项目经验", value: "8+", num: 8, suffix: "+" },
              { icon: Code2, label: "技术栈", value: "15+", num: 15, suffix: "+" },
            ].map((item) => (
              <motion.div
                key={item.label}
                whileHover={{ y: -4 }}
                className="hero-stat card p-4 text-center"
              >
                <div className="w-9 h-9 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center mx-auto mb-2 border border-blue-100">
                  <item.icon className="w-4 h-4" />
                </div>
                <div className="text-xl font-bold text-gray-900">
                  {item.num ? <AdvancedCounter target={item.num} suffix={item.suffix} /> : item.value}
                </div>
                <div className="text-xs text-gray-500 mt-0.5">{item.label}</div>
              </motion.div>
            ))}
          </div>

          {/* CTA 按钮 */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center pt-4">
            <motion.a
              href="#projects"
              whileHover={{ scale: 1.03, y: -2 }}
              whileTap={{ scale: 0.97 }}
              className="hero-cta btn-primary text-center group"
            >
              查看项目作品
              <ChevronRight className="w-4 h-4 inline-block ml-1 group-hover:translate-x-1 transition-transform" />
            </motion.a>
            <motion.a
              href="#contact"
              whileHover={{ scale: 1.03, y: -2 }}
              whileTap={{ scale: 0.97 }}
              className="hero-cta btn-secondary text-center"
            >
              联系我
            </motion.a>
          </div>
        </div>
      </div>

      {/* 滚动指示器 */}
      <div className="hero-scroll absolute bottom-8 left-1/2 -translate-x-1/2">
        <a
          href="#education"
          className="flex flex-col items-center gap-2 text-gray-400 hover:text-gray-600 transition-colors"
        >
          <span className="text-[10px] font-mono tracking-widest uppercase">Scroll</span>
          <ArrowDown className="w-4 h-4 animate-bounce" />
        </a>
      </div>
    </section>
  );
}

// src/components/HeroSection.vue
<template>
  <section class="relative min-h-screen flex items-center justify-center px-6 pt-20 overflow-hidden">
    <!-- 精美背景渐变 -->
    <div class="absolute inset-0 bg-gradient-to-br from-blue-50 via-white to-cyan-50 dark:from-gray-900 dark:via-gray-950 dark:to-blue-950"></div>
    
    <!-- 动态背景元素 -->
    <div class="absolute inset-0 overflow-hidden">
      <div class="absolute top-20 left-10 w-72 h-72 bg-gradient-to-br from-blue-400/20 to-cyan-400/20 rounded-full blur-3xl animate-pulse"></div>
      <div class="absolute bottom-20 right-10 w-96 h-96 bg-gradient-to-br from-cyan-400/20 to-blue-400/20 rounded-full blur-3xl animate-pulse" style="animation-delay: 1s"></div>
      <div class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-gradient-to-br from-blue-400/10 to-cyan-400/10 rounded-full blur-3xl"></div>
    </div>

    <div class="relative max-w-5xl w-full text-center z-10">
      <!-- 主标题 -->
      <div
        v-motion
        :initial="{ opacity: 0, y: 30 }"
        :enter="{ opacity: 1, y: 0, transition: { duration: 1000, ease: 'easeOut' } }"
        class="mb-8"
      >
        <div class="inline-block px-6 py-2 mb-6 glass-effect rounded-full">
          <span class="text-sm font-semibold gradient-text">CLOUD COMPUTING ENGINEER</span>
        </div>
        <h1 class="text-6xl md:text-8xl font-bold mb-6 text-gray-900 dark:text-white leading-tight">
          卓越的
          <span class="gradient-text-pink">云计算</span>
          <br>
          工程师
        </h1>
      </div>

      <!-- 打字机效果 -->
      <div
        v-motion
        :initial="{ opacity: 0 }"
        :enter="{ opacity: 1, transition: { delay: 400, duration: 800 } }"
        class="text-2xl md:text-3xl text-gray-600 dark:text-gray-400 min-h-[100px] font-medium flex items-center justify-center text-center mb-12"
      >
        <span class="gradient-text-cyan font-semibold">{{ currentTitle }}</span>
        <span class="animate-pulse ml-2 text-primary-500">|</span>
      </div>

      <!-- 介绍文字 -->
      <p
        v-motion
        :initial="{ opacity: 0, y: 20 }"
        :enter="{ opacity: 1, y: 0, transition: { delay: 800, duration: 800 } }"
        class="text-xl text-gray-600 dark:text-gray-400 max-w-3xl mx-auto mb-16 leading-relaxed"
      >
        重庆商务职业学院 · 云计算技术应用专业<br>
        <span class="gradient-text font-semibold">专注于云原生架构、容器化技术与 DevOps 实践</span>
      </p>

      <!-- 统计数据卡片 -->
      <div
        v-motion
        :initial="{ opacity: 0, y: 20 }"
        :enter="{ opacity: 1, y: 0, transition: { delay: 1200, duration: 800 } }"
        class="grid grid-cols-3 gap-6 max-w-3xl mx-auto mb-16"
      >
        <div
          v-for="(stat, index) in stats"
          :key="index"
          class="glass-effect rounded-2xl p-6 card-hover"
        >
          <div class="text-4xl md:text-5xl font-bold gradient-text mb-3">
            {{ stat.value }}
          </div>
          <div class="text-sm font-medium text-gray-600 dark:text-gray-400">
            {{ stat.label }}
          </div>
        </div>
      </div>

      <!-- CTA 按钮 -->
      <div
        v-motion
        :initial="{ opacity: 0, y: 20 }"
        :enter="{ opacity: 1, y: 0, transition: { delay: 1600, duration: 800 } }"
        class="flex flex-col sm:flex-row gap-6 justify-center items-center"
      >
        <a
          href="#contact"
          class="group relative px-10 py-5 bg-gradient-primary text-white rounded-2xl font-semibold text-lg overflow-hidden transition-all duration-300 hover:scale-105 hover:shadow-2xl shine-effect"
        >
          <span class="relative z-10">联系我</span>
        </a>
        <a
          href="#projects"
          class="px-10 py-5 glass-effect text-gray-700 dark:text-gray-300 rounded-2xl font-semibold text-lg transition-all duration-300 hover:scale-105 hover:shadow-2xl"
        >
          查看项目
        </a>
      </div>
      
      <!-- 滚动提示 -->
      <div
        v-motion
        :initial="{ opacity: 0 }"
        :enter="{ opacity: 1, transition: { delay: 2000, duration: 1000 } }"
        class="absolute bottom-10 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 text-gray-400 dark:text-gray-600"
      >
        <span class="text-sm font-medium">滚动探索</span>
        <div class="w-6 h-10 border-2 border-gray-300 dark:border-gray-700 rounded-full p-1">
          <div class="w-1.5 h-1.5 bg-gray-400 dark:bg-gray-600 rounded-full animate-bounce"></div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'

const titles = [
  '云原生架构师 in training',
  'DevOps 实践者',
  'Kubernetes 爱好者',
  '容器化技术专家'
]

const currentTitle = ref('')
const titleIndex = ref(0)
const charIndex = ref(0)
const isDeleting = ref(false)

const stats = [
  { value: '99.9%', label: '服务可用性' },
  { value: '80%', label: '效率提升' },
  { value: '24/7', label: '快速响应' }
]

let typingInterval: number

const typeEffect = () => {
  const currentText = titles[titleIndex.value]
  
  if (!isDeleting.value) {
    currentTitle.value = currentText.substring(0, charIndex.value + 1)
    charIndex.value++
    
    if (charIndex.value === currentText.length) {
      isDeleting.value = true
      return 2000 // 暂停2秒
    }
    return 100 // 打字速度
  } else {
    currentTitle.value = currentText.substring(0, charIndex.value - 1)
    charIndex.value--
    
    if (charIndex.value === 0) {
      isDeleting.value = false
      titleIndex.value = (titleIndex.value + 1) % titles.length
      return 500 // 切换标题前暂停
    }
    return 50 // 删除速度
  }
}

const startTyping = () => {
  const type = () => {
    const delay = typeEffect()
    typingInterval = window.setTimeout(type, delay)
  }
  type()
}

onMounted(() => {
  startTyping()
})

onUnmounted(() => {
  if (typingInterval) {
    clearTimeout(typingInterval)
  }
})
</script>

<style scoped>
.from-primary {
  --tw-gradient-from: #0070f3;
}

.to-accent {
  --tw-gradient-to: #00d4ff;
}
</style>
